version: "3"

services:
  database:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=adimn
      - POSTGRESQL_PASSWORD=admin123
      - POSTGRESQL_DATABASE=database
